// GENERATED by scripts/build-accuracy-headline.mjs. Do not edit by hand.
//
// The site's accuracy claims, in one place, so no page can quote a kinder
// number than the record supports. Regenerate after any results ingest.
//
// Read the distinction before using these:
//   outOfSample  published and hash-witnessed BEFORE the count, then scored.
//                This is the honest headline and the one to lead with.
//   running      regraded nightly as by-election results land, so it moves.
//   backtest     scored against an election the model was built against.
//                Context only. It must never be the headline figure.

export interface AccuracyRecord {
  label: string;
  winnerAccuracyPct: number;
  maePp: number;
}

export const ACCURACY_OUT_OF_SAMPLE = {
  "label": "May 2026 locked forecast",
  "ballots": 2903,
  "winnerAccuracyPct": 49.6,
  "maePp": 10.7
} as const;

export const ACCURACY_RUNNING = {
  "label": "Council by-elections since May 2025",
  "contests": 223,
  "winnerAccuracyPct": 60.5,
  "maePp": 7.7
} as const;

export const ACCURACY_BACKTEST_2024 = {
  "label": "May 2024 backtest",
  "winnerAccuracyPct": 82.7,
  "maePp": 5.7
} as const;

/** One line for the nav and meta descriptions. Leads with the hardest number. */
export const ACCURACY_HEADLINE =
  "May 2026 out-of-sample: 49.6% of winners, 10.7pp MAE";
