import { loadIdentity, loadGePredictions } from "./predictions";
import { getIndexableSitePaths } from "./site";

/**
 * Every URL the sitemap should carry.
 *
 * `getIndexableSitePaths()` in site.ts is a hand-maintained list of the ~35 static
 * routes. It cannot see the thousands of pages generated by `getStaticPaths()`, so
 * until this module existed the sitemap advertised 35 of the site's 3,820 pages and
 * every council, ward and parliamentary seat page was left to be discovered by crawl
 * alone. site.ts is deliberately import-free (the metadata tests load it), so the
 * dynamic half lives here instead.
 *
 * The slug expressions below must stay identical to the `getStaticPaths()` in
 * src/pages/seats/**. A drift test in tests/sitemap-paths.test.ts guards that.
 */

// Structurally compatible with IdentityWard in predictions.ts, which sets
// the nullable fields to `string | null` rather than leaving them absent.
// Declaring them `string | undefined` here made `identity.wards` fail to
// assign, so `astro check` has been red since this module landed.
type Ward = {
  tier?: string;
  council_slug?: string | null;
  ward_slug?: string | null;
  gss_code?: string | null;
  ballot_paper_id?: string | null;
};

/** Matches src/pages/seats/[council]/[ward]/index.astro. */
export function wardSlug(ward: Ward): string {
  return (
    ward.ward_slug ||
    ward.gss_code ||
    (ward.ballot_paper_id || "").split(".").slice(2, -1).join(".")
  );
}

function isElectedSeat(ward: Ward): boolean {
  return ward.tier === "local" || ward.tier === "mayor";
}

export function getSeatPaths(): string[] {
  const identity = loadIdentity();
  const wards: Ward[] = (identity.wards || []).filter(isElectedSeat);

  const councils = new Set<string>();
  const paths = new Set<string>();

  for (const ward of wards) {
    if (!ward.council_slug) continue;
    councils.add(ward.council_slug);
    const slug = wardSlug(ward);
    if (!slug) continue;
    paths.add(`/seats/${ward.council_slug}/${slug}/`);
  }
  for (const council of councils) {
    paths.add(`/seats/${council}/`);
  }
  return [...paths];
}

/** Matches src/pages/seats/parliament/[constituency]/index.astro. */
export function getParliamentSeatPaths(): string[] {
  // loadGePredictions() returns the whole constituencies.json, whose predictions
  // sit under a nested `predictions` key. The route unwraps it the same way.
  const bundle = loadGePredictions() as { predictions?: Record<string, unknown> };
  return Object.entries(bundle?.predictions || {})
    .filter(([, record]) => Boolean((record as { prediction?: unknown })?.prediction))
    .map(([slug]) => `/seats/parliament/${slug}/`);
}

export function getAllSitemapPaths(): string[] {
  const paths = new Set<string>([
    ...getIndexableSitePaths(),
    ...getSeatPaths(),
    ...getParliamentSeatPaths(),
  ]);
  return [...paths].sort((a, b) => a.localeCompare(b));
}
