import { existsSync, readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { loadIdentity, loadGePredictions } from "./predictions";
import { getIndexableSitePaths } from "./site";

/**
 * Every URL the sitemap should carry.
 *
 * `getIndexableSitePaths()` in site.ts is a hand-maintained list of the ~35 static
 * routes. It cannot see the thousands of pages generated by `getStaticPaths()`, so
 * until this module existed the sitemap advertised 35 of the site's 3,820 pages and
 * every council, ward and parliamentary seat page was left to be discovered by crawl
 * alone. site.ts is deliberately import-free (the metadata tests load it), so the
 * dynamic half lives here instead.
 *
 * The slug expressions below must stay identical to the `getStaticPaths()` in
 * src/pages/seats/**. A drift test in tests/sitemap-paths.test.ts guards that.
 */

// Structurally compatible with IdentityWard in predictions.ts, which sets
// the nullable fields to `string | null` rather than leaving them absent.
// Declaring them `string | undefined` here made `identity.wards` fail to
// assign, so `astro check` has been red since this module landed.
type Ward = {
  tier?: string;
  council_slug?: string | null;
  ward_slug?: string | null;
  gss_code?: string | null;
  ballot_paper_id?: string | null;
};

/** Matches src/pages/seats/[council]/[ward]/index.astro. */
export function wardSlug(ward: Ward): string {
  return (
    ward.ward_slug ||
    ward.gss_code ||
    (ward.ballot_paper_id || "").split(".").slice(2, -1).join(".")
  );
}

function isElectedSeat(ward: Ward): boolean {
  return ward.tier === "local" || ward.tier === "mayor";
}

export function getSeatPaths(): string[] {
  const identity = loadIdentity();
  const wards: Ward[] = (identity.wards || []).filter(isElectedSeat);

  const councils = new Set<string>();
  const paths = new Set<string>();

  for (const ward of wards) {
    if (!ward.council_slug) continue;
    councils.add(ward.council_slug);
    const slug = wardSlug(ward);
    if (!slug) continue;
    paths.add(`/seats/${ward.council_slug}/${slug}/`);
  }
  for (const council of councils) {
    paths.add(`/seats/${council}/`);
  }
  return [...paths];
}

/** Matches src/pages/seats/parliament/[constituency]/index.astro. */
export function getParliamentSeatPaths(): string[] {
  // loadGePredictions() returns the whole constituencies.json, whose predictions
  // sit under a nested `predictions` key. The route unwraps it the same way.
  const bundle = loadGePredictions() as { predictions?: Record<string, unknown> };
  return Object.entries(bundle?.predictions || {})
    .filter(([, record]) => Boolean((record as { prediction?: unknown })?.prediction))
    .map(([slug]) => `/seats/parliament/${slug}/`);
}

/**
 * Matches src/pages/by-elections/local/[slug].astro.
 *
 * The contest directory is rebuilt on every data refresh and contests age out
 * of it, so this reads the directory rather than any list held elsewhere. An
 * absent directory is normal on a fresh clone before the first build.
 */
export function getLocalByElectionPaths(): string[] {
  const dir = path.join(process.cwd(), "data/contests/local-byelections");
  if (!existsSync(dir)) return [];
  const paths = readdirSync(dir)
    .filter((f) => f.endsWith(".json") && !f.startsWith("_"))
    .map((f) => `/by-elections/local/${f.replace(/\.json$/, "")}/`);
  return paths.length ? ["/by-elections/local/", ...paths] : [];
}

/**
 * `lastmod` for the paths that have a real content date, and only those.
 *
 * Google ignores a lastmod it cannot trust, and stamping every one of the ~3,900
 * URLs with the nightly build time is exactly the pattern that earns that
 * distrust: it would claim the whole site changed daily when almost none of it
 * did. So this covers council by-election pages alone, where the date is a fact
 * in the contest file (polls closed on polling day) and where freshness is what
 * the traffic actually turns on. Everything else is emitted without a lastmod,
 * which is a valid and more honest sitemap than a uniform one.
 */
export function getLastmodByPath(
  dirAbs = path.join(process.cwd(), "data/contests/local-byelections")
): Record<string, string> {
  const dir = dirAbs;
  if (!existsSync(dir)) return {};
  const out: Record<string, string> = {};

  for (const file of readdirSync(dir)) {
    if (!file.endsWith(".json") || file.startsWith("_")) continue;
    let contest: { contest?: { polling_day?: string }; slug?: string };
    try {
      contest = JSON.parse(readFileSync(path.join(dir, file), "utf8"));
    } catch {
      continue;
    }
    const pollingDay = contest?.contest?.polling_day;
    const slug = contest?.slug;
    if (!pollingDay || !slug) continue;
    // Date-only is a valid sitemap lastmod and is all this claims to know: the
    // page settled once the count was in.
    out[`/by-elections/local/${slug}/`] = pollingDay;
  }

  return out;
}

export function getAllSitemapPaths(): string[] {
  const paths = new Set<string>([
    ...getIndexableSitePaths(),
    ...getSeatPaths(),
    ...getParliamentSeatPaths(),
    ...getLocalByElectionPaths(),
  ]);
  return [...paths].sort((a, b) => a.localeCompare(b));
}
